### ISSUE TITLE
Problem Firefox Ubuntu

### ISSUE THREAD

**Issue by Machou** [WesleyBranton/Remove-Firefox-Megabar#3]
Hi :)

Don't work on white page on Ubuntu Firefox 80.0.1

I can't put a screenshot because when I do it the bar normally resets lol, it's only when I open a new tab that it's big.

**Comment by WesleyBranton** [comment]
I'm not able to reproduce this issue on Ubuntu.

When you say it expands, do you mean that the bar itself is actually growing or do you mean that the list of top sites is displaying in the drop-down menu automatically?

**Comment by Machou** [comment]
No, when I open a new tab, the bar is golden, I have to press a key for it to recover normally (in small)

look the video : https://vimeo.com/458052410

**Comment by WesleyBranton** [comment]
I've looked into this some more and tried it on some other Ubuntu devices and I'm still not able to reproduce this issue. Make sure that you are running the latest version of the CSS code and try commenting out or deleting any other code that you may have in your `userChrome.css` file.

**Comment by Machou** [comment]
Sorry i have missed : toolkit.legacyUserProfileCustomizations.stylesheets
