### ISSUE TITLE
Update for Firefox 126

### ISSUE THREAD

**Issue by WesleyBranton** [WesleyBranton/Remove-Firefox-Megabar#8]
It seems that the expanding URL is back :(
I've revived this repo and it seems the current code does not work with Firefox 126.

**Comment by Walkman100** [comment]
Just updated to FF 128, some expanding was back. I've managed to figure out what it is, they changed the class `urlbar-input-container` to an ID, so changing https://github.com/WesleyBranton/Remove-Firefox-Megabar/blob/449943563ae7487cbb5e5c1a17098f7f3565b061/remove_megabar.css#L13 to this works:

```css
#urlbar[breakout][breakout-extend] > .urlbar-input-container {
```

**Comment by WesleyBranton** [comment]
Thanks @Walkman100! I was going to look into this today and now it will be easier since you have identified the problem.
